server:
    port: 8080
logging:
  level:
    root: warn
    com.glodon: info
  file: ./log/datasync.log
  

spring:
  servlet:
    multipart:
      max-file-size: 30MB     #单个文件 最大尺寸(设置30)
      max-request-size: 100MB #一个请求 文件的最大尺寸 

# ===================================
# 分布式文件系统FDFS配置
# ===================================
fdfs:
  so-timeout: 1501           #连接超时时间
  connect-timeout: 1601      #读取超时时间
  webServerUrl: http://192.168.124.128:8888/
  thumb-image:             #缩略图生成参数
    width: 200
    height: 200
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.124.128:22122
